(() => {
  const KEY = 'aida-os-data-v1';
  const defaults = { clients: [], opportunities: [], tasks: [] };
  let data = load(), view = 'overview', taskFilter = 'active', editing = null;
  const $ = s => document.querySelector(s);
  const els = { content: $('#viewContent'), title: $('#viewTitle'), form: $('#entryForm'), fields: $('#formFields'), entry: $('#entryDialog'), detail: $('#detailDialog'), command: $('#commandDialog'), toast: $('#toast') };
  const services = ['Positioning', 'Sales', 'Marketing', 'Photo & Video', 'Software'];
  const team = [{n:'Posicionamiento',r:'Posicionamiento'}, {n:'Ventas',r:'Ventas'}, {n:'Marketing',r:'Marketing / Foto & Video'}, {n:'Software',r:'Software'}];
  function load(){ try { const parsed = JSON.parse(localStorage.getItem(KEY)); return parsed && ['clients','opportunities','tasks'].every(k => Array.isArray(parsed[k])) ? parsed : structuredClone(defaults); } catch { return structuredClone(defaults); } }
  function save(){ localStorage.setItem(KEY, JSON.stringify(data)); }
  function id(){ return crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36)+Math.random().toString(36).slice(2); }
  function esc(v=''){ return String(v).replace(/[&<>"]/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m])); }
  function today(){ $('#today').textContent = new Intl.DateTimeFormat('es-EC',{weekday:'long',day:'numeric',month:'long'}).format(new Date()); }
  function money(v){ return v ? new Intl.NumberFormat('es-EC',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v)) : '—'; }
  function label(v){ return `<span class="badge ${/Won|Alta|Vencida/.test(v)?'teal':/Lost|Baja/.test(v)?'coral':''}">${esc(v)}</span>`; }
  function empty(title, copy, kind){ return `<section class="empty"><h3>${title}</h3><p>${copy}</p><button class="primary-button" data-add="${kind}">Crear ${kind === 'client' ? 'cliente' : kind === 'opportunity' ? 'oportunidad' : 'tarea'}</button></section>`; }
  function render(){
    els.title.textContent = ({overview:'Resumen',clients:'Clientes',opportunities:'Oportunidades',projects:'Proyectos',tasks:'Tareas',team:'Equipo',settings:'Ajustes'})[view];
    document.querySelectorAll('.nav-link[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
    const fn = {overview:overview, clients:clients, opportunities:opportunities, projects:projects, tasks:tasks, team:teamView, settings:settings}[view]; fn();
  }
  function overview(){ const open=data.opportunities.filter(o=>!['Won','Lost'].includes(o.stage)), due=data.tasks.filter(t=>!t.completed && t.due && new Date(t.due+'T23:59:59') <= new Date()); const total=open.reduce((s,o)=>s+(Number(o.value)||0),0);
    els.content.innerHTML=`<div class="overview"><section class="welcome"><div><p class="eyebrow">ESPACIO DE OPERACIONES</p><h2>Un lugar tranquilo para que el trabajo avance.</h2><p>Registra una relación, una conversación comercial o el siguiente paso. AIDA OS organiza lo que tu equipo decide guardar aquí.</p></div><div class="loop-art" aria-hidden="true"></div></section><section class="action-strip"><button class="action-card" data-add="client"><b>Añadir un cliente</b><span>Una relación y su contexto</span></button><button class="action-card" data-add="opportunity"><b>Registrar oportunidad</b><span>Una conversación comercial</span></button><button class="action-card" data-add="task"><b>Crear una tarea</b><span>El próximo paso del equipo</span></button></section><h3 class="section-title">Pulso del espacio</h3><section class="metrics"><div class="metric"><b>${data.clients.filter(c=>c.status==='Activo').length}</b><span>Clientes activos</span></div><div class="metric"><b>${open.length}</b><span>Oportunidades abiertas</span></div><div class="metric"><b>${money(total)}</b><span>Pipeline estimado</span></div><div class="metric"><b>${due.length}</b><span>Tareas vencidas</span></div></section>${data.clients.length||data.opportunities.length||data.tasks.length?'':'<p class="local-note" style="color:var(--muted);padding:18px 0">Este resumen se actualizará con los datos que añadas. Nada se comparte fuera de este navegador.</p>'}</div>`; }
  function moduleHead(title, copy, kind, filters=''){ return `<div class="module-head"><div><h2>${title}</h2><p>${copy}</p></div><div style="display:flex;gap:10px;align-items:center">${filters}<button class="primary-button" data-add="${kind}">+ Añadir</button></div></div>`; }
  function clients(){ const rows=data.clients.map(c=>`<button class="record" data-detail="client" data-id="${c.id}"><div><b>${esc(c.name)}</b><small>${esc(c.company||'Sin empresa')}</small></div><div class="hide-mobile">${esc(c.service||'Sin servicio')}</div><div class="hide-mobile">${esc(c.nextAction||'Sin siguiente paso')}</div><div>${label(c.status)}</div></button>`).join(''); els.content.innerHTML=`<div class="module">${moduleHead('Clientes','Relaciones activas y sus próximos pasos.','client')}${rows?`<section class="records">${rows}</section>`:empty('Aún no hay clientes','Comienza con una relación real. Podrás conservar el contexto y el próximo paso.', 'client')}</div>`; }
  function opportunities(){ const rows=data.opportunities.map(o=>`<button class="record" data-detail="opportunity" data-id="${o.id}"><div><b>${esc(o.name)}</b><small>${esc(o.client||'Sin cliente asociado')}</small></div><div class="hide-mobile">${esc(o.service)}</div><div class="hide-mobile">${money(o.value)}</div><div>${label(o.stage)}</div></button>`).join(''); els.content.innerHTML=`<div class="module">${moduleHead('Oportunidades','Conversaciones comerciales que requieren atención.','opportunity')}${rows?`<section class="records">${rows}</section>`:empty('La bandeja está lista','Registra una oportunidad cuando aparezca una conversación comercial concreta.', 'opportunity')}</div>`; }
  function projects(){ els.content.innerHTML=`<div class="module">${moduleHead('Proyectos','Espacio reservado para la planificación de entregables.','task')}<section class="empty"><h3>Los proyectos llegan después del acuerdo.</h3><p>En esta primera versión, usa clientes, oportunidades y tareas para sostener el trabajo. La planificación de proyectos todavía no guarda registros.</p></section></div>`; }
  function tasks(){ const list=data.tasks.filter(t=>taskFilter==='completed'?t.completed:!t.completed); const filters=`<div class="filter-group"><button data-filter="active" class="${taskFilter==='active'?'active':''}">Activas</button><button data-filter="completed" class="${taskFilter==='completed'?'active':''}">Completadas</button></div>`; const rows=list.map(t=>`<div class="record"><label style="display:flex;align-items:center;gap:12px;cursor:pointer"><input class="task-check" data-id="${t.id}" type="checkbox" ${t.completed?'checked':''} aria-label="Completar ${esc(t.title)}"><span><b>${esc(t.title)}</b><small>${esc(t.client||'Sin cliente')}</small></span></label><div class="hide-mobile">${esc(t.owner||'Sin asignar')}</div><div class="hide-mobile">${t.due?new Intl.DateTimeFormat('es-EC',{day:'numeric',month:'short'}).format(new Date(t.due+'T12:00:00')):'Sin fecha'}</div><button class="badge ${t.priority==='Alta'?'coral':''}" data-detail="task" data-id="${t.id}">${esc(t.priority)}</button></div>`).join(''); els.content.innerHTML=`<div class="module">${moduleHead('Tareas','Pequeños compromisos que mueven el trabajo.','task',filters)}${rows?`<section class="records">${rows}</section>`:empty(taskFilter==='completed'?'Nada completado todavía':'No hay tareas activas',taskFilter==='completed'?'Las tareas que marques como listas aparecerán aquí.':'Crea la próxima acción que el equipo necesita resolver.', 'task')}</div>`; }
  function teamView(){ els.content.innerHTML=`<div class="module"><div class="module-head"><div><h2>Equipo</h2><p>El núcleo de cuatro disciplinas de AIDA.</p></div></div><section class="team-grid">${team.map(x=>`<article class="team-member"><i>${x.n[0]}</i><b>${x.n}</b><span>${x.r}</span></article>`).join('')}</section></div>`; }
  function settings(){ els.content.innerHTML=`<div class="module settings"><div class="module-head"><div><h2>Ajustes</h2><p>Herramientas de este espacio local.</p></div></div><section class="setting-block"><h3>Respaldo de datos</h3><p>Exporta o importa un archivo JSON. Los datos se guardan únicamente en este navegador; importar reemplaza el espacio actual tras tu confirmación.</p><button class="secondary-button" id="exportData">Exportar JSON</button><button class="secondary-button" id="importData">Importar JSON</button></section><section class="setting-block"><h3>Borrar espacio de trabajo</h3><p>Elimina clientes, oportunidades y tareas de este navegador. Esta acción no se puede deshacer.</p><button class="secondary-button danger" id="clearData">Borrar espacio</button></section></div>`; }
  const field=(n,l,type='text',opts='',full=false,required=false)=>`<div class="field ${full?'full':''}"><label for="f-${n}">${l}${required?' *':''}</label>${type==='select'?`<select id="f-${n}" name="${n}" ${required?'required':''}>${opts}</select>`:type==='textarea'?`<textarea id="f-${n}" name="${n}"></textarea>`:`<input id="f-${n}" name="${n}" type="${type}" ${required?'required':''}>`}</div>`;
  function formFields(kind, item={}){ const status=['Activo','Pausa','Prospecto']; if(kind==='client')return field('name','Nombre','text','',false,true)+field('company','Empresa')+field('service','Servicio','select',`<option value="">Selecciona</option>${services.map(x=>`<option>${x}</option>`).join('')}`)+field('status','Estado','select',status.map(x=>`<option>${x}</option>`).join(''))+field('contact','Contacto')+field('email','Correo','email')+field('phone','Teléfono','tel')+field('nextAction','Próxima acción','text','',true)+field('notes','Notas','textarea','',true); if(kind==='opportunity')return field('name','Oportunidad','text','',false,true)+field('client','Cliente o empresa')+field('service','Servicio','select',services.map(x=>`<option>${x}</option>`).join(''),false,true)+field('value','Valor estimado (USD)','number')+field('stage','Etapa','select',['New lead','Discovery','Proposal','Won','Lost'].map(x=>`<option>${x}</option>`).join(''))+field('nextAction','Próxima acción','text','',true); return field('title','Título de tarea','text','',true,true)+field('client','Cliente')+field('owner','Responsable / disciplina','select',`<option value="">Sin asignar</option>${team.map(x=>`<option>${x.r}</option>`).join('')}`)+field('due','Fecha límite','date')+field('priority','Prioridad','select','<option>Alta</option><option selected>Media</option><option>Baja</option>')+field('status','Estado','select','<option>Pendiente</option><option>En curso</option><option>En espera</option>'); }
  function openEntry(kind, item=null){ editing=item?{kind,id:item.id}:null; $('#dialogType').textContent=item?'EDITAR REGISTRO':'NUEVO REGISTRO'; $('#dialogTitle').textContent=item?'Editar '+({client:'cliente',opportunity:'oportunidad',task:'tarea'}[kind]):'Nuevo '+({client:'cliente',opportunity:'oportunidad',task:'tarea'}[kind]); els.fields.innerHTML=formFields(kind,item||{}); els.form.dataset.kind=kind; if(item) Object.entries(item).forEach(([k,v])=>{const e=els.form.elements[k];if(e)e.value=v??''}); els.entry.showModal(); els.form.querySelector('input')?.focus(); }
  function details(kind,id){ const item=data[kind==='client'?'clients':kind==='opportunity'?'opportunities':'tasks'].find(x=>x.id===id); if(!item)return; editing={kind,id}; $('#detailType').textContent=kind==='client'?'CLIENTE':kind==='opportunity'?'OPORTUNIDAD':'TAREA'; $('#detailTitle').textContent=item.name||item.title; const omit=['id','completed']; $('#detailBody').innerHTML=`<div class="detail-list">${Object.entries(item).filter(([k])=>!omit.includes(k)).map(([k,v])=>`<div class="detail-item ${k==='notes'||k==='nextAction'?'full':''}"><span>${({name:'Nombre',title:'Tarea',company:'Empresa',service:'Servicio',contact:'Contacto',email:'Correo',phone:'Teléfono',status:'Estado',nextAction:'Próxima acción',notes:'Notas',client:'Cliente / empresa',value:'Valor estimado',stage:'Etapa',owner:'Responsable',due:'Fecha límite',priority:'Prioridad'}[k]||k)}</span><b>${k==='value'?money(v):esc(v||'—')}</b></div>`).join('')}</div>`; els.detail.showModal(); }
  function toast(msg){ els.toast.textContent=msg;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),2300); }
  document.addEventListener('click', e=>{ const add=e.target.closest('[data-add]');if(add)openEntry(add.dataset.add);const nav=e.target.closest('[data-view]');if(nav){view=nav.dataset.view;render();closeMenu()}const det=e.target.closest('[data-detail]');if(det)details(det.dataset.detail,det.dataset.id);const fil=e.target.closest('[data-filter]');if(fil){taskFilter=fil.dataset.filter;tasks()}if(e.target.id==='exportData'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='aida-os-respaldo.json';a.click();URL.revokeObjectURL(a.href)}if(e.target.id==='importData')$('#importInput').click();if(e.target.id==='clearData'&&confirm('¿Borrar todo el espacio local? Esta acción no se puede deshacer.')){data=structuredClone(defaults);save();render();toast('Espacio de trabajo borrado.')} });
  els.form.addEventListener('submit',e=>{e.preventDefault();const kind=els.form.dataset.kind, values=Object.fromEntries(new FormData(els.form));const group=kind==='client'?'clients':kind==='opportunity'?'opportunities':'tasks'; if(editing){const i=data[group].findIndex(x=>x.id===editing.id);data[group][i]={...data[group][i],...values};toast('Cambios guardados.')}else{data[group].unshift({...values,id:id(),...(kind==='task'?{completed:false}:{})});toast('Registro guardado.')}save();els.entry.close();render();});
  document.addEventListener('change',e=>{if(e.target.classList.contains('task-check')){const t=data.tasks.find(x=>x.id===e.target.dataset.id);t.completed=e.target.checked;save();tasks();toast(t.completed?'Tarea completada.':'Tarea reabierta.')} });
  $('#detailClose').onclick=$('#detailCloseBottom').onclick=()=>els.detail.close();$('#detailEdit').onclick=()=>{els.detail.close();const g=editing.kind==='client'?'clients':editing.kind==='opportunity'?'opportunities':'tasks';openEntry(editing.kind,data[g].find(x=>x.id===editing.id));};
  $('#newButton').onclick=$('#mobileNew').onclick=()=>els.command.showModal();$('#commandClose').onclick=()=>els.command.close();document.querySelectorAll('.command-list button').forEach(b=>b.onclick=()=>{els.command.close();openEntry(b.dataset.kind)});
  $('#importInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!d||!['clients','opportunities','tasks'].every(k=>Array.isArray(d[k])))throw Error();if(confirm('¿Reemplazar los datos actuales con este respaldo?')){data=d;save();render();toast('Respaldo importado.')}}catch{alert('El archivo no tiene el formato de respaldo de AIDA OS.')}};r.readAsText(f);e.target.value='';});
  $('#searchInput').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();if(!q){render();return}const found=[...data.clients.map(x=>({...x,_:'client',title:x.name})),...data.opportunities.map(x=>({...x,_:'opportunity',title:x.name})),...data.tasks.map(x=>({...x,_:'task',title:x.title}))].filter(x=>Object.values(x).some(v=>String(v).toLowerCase().includes(q)));els.title.textContent='Búsqueda';els.content.innerHTML=`<div class="module"><div class="module-head"><div><h2>${found.length} resultado${found.length===1?'':'s'}</h2><p>Coincidencias para “${esc(e.target.value)}”.</p></div></div>${found.length?`<section class="records">${found.map(x=>`<button class="record" data-detail="${x._}" data-id="${x.id}"><div><b>${esc(x.title)}</b><small>${x._==='client'?'Cliente':x._==='opportunity'?'Oportunidad':'Tarea'}</small></div><div class="hide-mobile">${esc(x.client||x.company||x.service||'')}</div><div></div><div>${label(x.status||x.stage||x.priority||'')}</div></button>`).join('')}</section>`:'<section class="empty"><h3>No encontramos registros</h3><p>Prueba otro término o crea un registro nuevo.</p></section>'}</div>`;});
  function closeMenu(){$('#sidebar').classList.remove('open');$('#backdrop').classList.remove('active');$('#menuButton').setAttribute('aria-expanded','false')}$('#menuButton').onclick=()=>{const open=$('#sidebar').classList.toggle('open');$('#backdrop').classList.toggle('active',open);$('#menuButton').setAttribute('aria-expanded',open)};$('#backdrop').onclick=closeMenu;
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();return}if(e.key.toLowerCase()==='n'&&!e.metaKey&&!e.ctrlKey&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();els.command.showModal()}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchInput').focus()}});
  today();render();
})();
