(() => {
  const KEY = 'aida-os-data-v1';
  const defaults = { clients: [], opportunities: [], tasks: [] };
  let data = load(), view = 'overview', taskFilter = 'active', editing = null, toastTimer;
  const $ = s => document.querySelector(s);
  const els = { content: $('#viewContent'), title: $('#viewTitle'), form: $('#entryForm'), fields: $('#formFields'), entry: $('#entryDialog'), detail: $('#detailDialog'), command: $('#commandDialog'), toast: $('#toast') };
  const services = ['Positioning', 'Sales', 'Marketing', 'Photo & Video', 'Software'];
  const team = [{n:'Agustín',r:'Posicionamiento',image:'agustin'}, {n:'Ricardo',r:'Ventas',image:'ricardo'}, {n:'Jeremy',r:'Marketing / Foto & Video',image:'jeremy'}, {n:'Nath',r:'Software',image:'nath'}];
  function load(){ try { const parsed = JSON.parse(localStorage.getItem(KEY)); return parsed && ['clients','opportunities','tasks'].every(k => Array.isArray(parsed[k])) ? parsed : structuredClone(defaults); } catch { return structuredClone(defaults); } }
  function save(){ localStorage.setItem(KEY, JSON.stringify(data)); }
  function id(){ return crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36)+Math.random().toString(36).slice(2); }
  function esc(v=''){ return String(v).replace(/[&<>"]/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m])); }
  function today(){ $('#today').textContent = new Intl.DateTimeFormat('es-EC',{weekday:'long',day:'numeric',month:'long'}).format(new Date()); }
  function money(v){ return v ? new Intl.NumberFormat('es-EC',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v)) : '—'; }
  function label(v){ return `<span class="badge ${/Won|Alta|Vencida/.test(v)?'teal':/Lost|Baja/.test(v)?'coral':''}">${esc(v)}</span>`; }
  function empty(title, copy, kind){ return `<section class="empty"><h3>${title}</h3><p>${copy}</p><button class="primary-button" data-add="${kind}">Crear ${kind === 'client' ? 'cliente' : kind === 'opportunity' ? 'oportunidad' : 'tarea'}</button></section>`; }
  function render(){
    els.title.textContent = ({overview:'Dashboard',clients:'Clientes',opportunities:'Oportunidades',projects:'Proyectos',tasks:'Tareas',team:'Equipo',settings:'Ajustes'})[view];
    document.querySelectorAll('.nav-link[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
    const fn = {overview:overview, clients:clients, opportunities:opportunities, projects:projects, tasks:tasks, team:teamView, settings:settings}[view]; fn();
  }
  function overview(){
    const now=new Date(), open=data.opportunities.filter(o=>!['Won','Lost'].includes(o.stage)), active=data.tasks.filter(t=>!t.completed), due=active.filter(t=>t.due&&new Date(t.due+'T23:59:59')<now), ordered=[...active].sort((a,b)=>(a.due||'9999-12-31').localeCompare(b.due||'9999-12-31'));
    const taskCard=t=>`<button class="rail-task ${t.due&&new Date(t.due+'T23:59:59')<now?'overdue':''}" data-detail="task" data-id="${t.id}"><b>${esc(t.title)}</b><small>${t.due?new Intl.DateTimeFormat('es-EC',{day:'numeric',month:'short'}).format(new Date(t.due+'T12:00:00')):'Sin fecha'}${t.client?' · '+esc(t.client):''}</small></button>`;
    const stage=s=>{const list=open.filter(o=>o.stage===s);return `<section class="stage"><h4>${s}</h4>${list.length?list.map(o=>`<button class="stage-card" data-detail="opportunity" data-id="${o.id}"><b>${esc(o.name)}</b><small>${esc(o.client||'Sin cliente asociado')}</small></button>`).join(''):`<p class="stage-empty">Aún no hay oportunidades en esta etapa.</p>`}</section>`};
    els.content.innerHTML=`<div class="overview"><section class="dashboard-intro"><div><h2>Trabajo claro, datos reales.</h2><p>Este dashboard se actualiza sólo con los registros que tu equipo crea en AIDA OS.</p></div><section class="action-strip" aria-label="Crear"><button class="action-card" data-add="client"><b>Cliente</b><span>Nueva relación</span></button><button class="action-card" data-add="opportunity"><b>Oportunidad</b><span>Nuevo seguimiento</span></button><button class="action-card" data-add="task"><b>Tarea</b><span>Próximo paso</span></button></section></section><section class="metrics" aria-label="Indicadores"><div class="metric"><b>${data.clients.filter(c=>c.status==='Activo').length}</b><span>Clientes activos</span></div><div class="metric"><b>${open.length}</b><span>Pipeline abierto</span></div><div class="metric"><b>${active.length}</b><span>Tareas activas</span></div><div class="metric"><b>${due.length}</b><span>Tareas vencidas</span></div></section><section class="dashboard-grid"><section class="panel"><div class="panel-head"><h3>Pipeline</h3><span>Oportunidades abiertas</span></div><div class="pipeline">${stage('New lead')}${stage('Discovery')}${stage('Proposal')}</div></section><aside class="panel"><div class="panel-head"><h3>Tareas activas</h3><span>${active.length}</span></div><div class="rail-list">${ordered.slice(0,5).map(taskCard).join('')||'<p class="stage-empty">No hay tareas activas. Crea el siguiente paso cuando lo necesites.</p>'}</div></aside></section><section class="panel followup"><div class="panel-head"><h3>Seguimiento</h3><span>Próximas fechas</span></div>${ordered.length?`<div class="followup-grid">${ordered.slice(0,5).map(t=>`<button class="due-card" data-detail="task" data-id="${t.id}"><time>${t.due?new Intl.DateTimeFormat('es-EC',{day:'numeric',month:'short'}).format(new Date(t.due+'T12:00:00')):'Sin fecha'}</time><b>${esc(t.title)}</b></button>`).join('')}</div>`:'<p class="stage-empty">Crea una tarea con fecha límite para verla en este calendario de seguimiento.</p>'}</section></div>`;
  }
  function moduleHead(title, copy, kind, filters=''){ return `<div class="module-head"><div><h2>${title}</h2><p>${copy}</p></div><div style="display:flex;gap:10px;align-items:center">${filters}<button class="primary-button" data-add="${kind}">+ Añadir</button></div></div>`; }
  function clients(){ const rows=data.clients.map(c=>`<button class="record" data-detail="client" data-id="${c.id}"><div><b>${esc(c.name)}</b><small>${esc(c.company||'Sin empresa')}</small></div><div class="hide-mobile">${esc(c.service||'Sin servicio')}</div><div class="hide-mobile">${esc(c.nextAction||'Sin siguiente paso')}</div><div>${label(c.status)}</div></button>`).join(''); els.content.innerHTML=`<div class="module">${moduleHead('Clientes','Relaciones activas y sus próximos pasos.','client')}${rows?`<section class="records">${rows}</section>`:empty('Aún no hay clientes','Comienza con una relación real. Podrás conservar el contexto y el próximo paso.', 'client')}</div>`; }
  function opportunities(){ const rows=data.opportunities.map(o=>`<button class="record" data-detail="opportunity" data-id="${o.id}"><div><b>${esc(o.name)}</b><small>${esc(o.client||'Sin cliente asociado')}</small></div><div class="hide-mobile">${esc(o.service)}</div><div class="hide-mobile">${money(o.value)}</div><div>${label(o.stage)}</div></button>`).join(''); els.content.innerHTML=`<div class="module">${moduleHead('Oportunidades','Conversaciones comerciales que requieren atención.','opportunity')}${rows?`<section class="records">${rows}</section>`:empty('La bandeja está lista','Registra una oportunidad cuando aparezca una conversación comercial concreta.', 'opportunity')}</div>`; }
  function projects(){ els.content.innerHTML=`<div class="module">${moduleHead('Proyectos','Espacio reservado para la planificación de entregables.','task')}<section class="empty"><h3>Los proyectos llegan después del acuerdo.</h3><p>En esta primera versión, usa clientes, oportunidades y tareas para sostener el trabajo. La planificación de proyectos todavía no guarda registros.</p></section></div>`; }
  function tasks(){ const list=data.tasks.filter(t=>taskFilter==='completed'?t.completed:!t.completed); const filters=`<div class="filter-group"><button data-filter="active" class="${taskFilter==='active'?'active':''}">Activas</button><button data-filter="completed" class="${taskFilter==='completed'?'active':''}">Completadas</button></div>`; const rows=list.map(t=>`<div class="record"><label style="display:flex;align-items:center;gap:12px;cursor:pointer"><input class="task-check" data-id="${t.id}" type="checkbox" ${t.completed?'checked':''} aria-label="Completar ${esc(t.title)}"><span><b>${esc(t.title)}</b><small>${esc(t.client||'Sin cliente')}</small></span></label><div class="hide-mobile">${esc(t.owner||'Sin asignar')}</div><div class="hide-mobile">${t.due?new Intl.DateTimeFormat('es-EC',{day:'numeric',month:'short'}).format(new Date(t.due+'T12:00:00')):'Sin fecha'}</div><button class="badge ${t.priority==='Alta'?'coral':''}" data-detail="task" data-id="${t.id}">${esc(t.priority)}</button></div>`).join(''); els.content.innerHTML=`<div class="module">${moduleHead('Tareas','Pequeños compromisos que mueven el trabajo.','task',filters)}${rows?`<section class="records">${rows}</section>`:empty(taskFilter==='completed'?'Nada completado todavía':'No hay tareas activas',taskFilter==='completed'?'Las tareas que marques como listas aparecerán aquí.':'Crea la próxima acción que el equipo necesita resolver.', 'task')}</div>`; }
  function teamView(){ els.content.innerHTML=`<div class="module"><div class="module-head"><div><h2>Equipo</h2><p>El núcleo de cuatro disciplinas de AIDA.</p></div></div><section class="team-grid">${team.map(x=>`<article class="team-member"><img src="assets/team/${x.image}.jpg" alt="${x.n}"><div><b>${x.n}</b><span>${x.r}</span></div></article>`).join('')}</section></div>`; }
  function settings(){ els.content.innerHTML=`<div class="module settings"><div class="module-head"><div><h2>Ajustes</h2><p>Herramientas de este espacio local.</p></div></div><section class="setting-block"><h3>Respaldo de datos</h3><p>Exporta o importa un archivo JSON. Los datos se guardan únicamente en este navegador; importar reemplaza el espacio actual tras tu confirmación.</p><button class="secondary-button" id="exportData">Exportar JSON</button><button class="secondary-button" id="importData">Importar JSON</button></section><section class="setting-block"><h3>Borrar espacio de trabajo</h3><p>Elimina clientes, oportunidades y tareas de este navegador. Esta acción no se puede deshacer.</p><button class="secondary-button danger" id="clearData">Borrar espacio</button></section></div>`; }
  const field=(n,l,type='text',opts='',full=false,required=false)=>`<div class="field ${full?'full':''}"><label for="f-${n}">${l}${required?' *':''}</label>${type==='select'?`<select id="f-${n}" name="${n}" ${required?'required':''}>${opts}</select>`:type==='textarea'?`<textarea id="f-${n}" name="${n}"></textarea>`:`<input id="f-${n}" name="${n}" type="${type}" ${required?'required':''}>`}</div>`;
  function formFields(kind, item={}){ const status=['Activo','Pausa','Prospecto']; if(kind==='client')return field('name','Nombre','text','',false,true)+field('company','Empresa')+field('service','Servicio','select',`<option value="">Selecciona</option>${services.map(x=>`<option>${x}</option>`).join('')}`)+field('status','Estado','select',status.map(x=>`<option>${x}</option>`).join(''))+field('contact','Contacto')+field('email','Correo','email')+field('phone','Teléfono','tel')+field('nextAction','Próxima acción','text','',true)+field('notes','Notas','textarea','',true); if(kind==='opportunity')return field('name','Oportunidad','text','',false,true)+field('client','Cliente o empresa')+field('service','Servicio','select',services.map(x=>`<option>${x}</option>`).join(''),false,true)+field('value','Valor estimado (USD)','number')+field('stage','Etapa','select',['New lead','Discovery','Proposal','Won','Lost'].map(x=>`<option>${x}</option>`).join(''))+field('nextAction','Próxima acción','text','',true); return field('title','Título de tarea','text','',true,true)+field('client','Cliente')+field('owner','Responsable / disciplina','select',`<option value="">Sin asignar</option>${team.map(x=>`<option>${x.r}</option>`).join('')}`)+field('due','Fecha límite','date')+field('priority','Prioridad','select','<option>Alta</option><option selected>Media</option><option>Baja</option>')+field('status','Estado','select','<option>Pendiente</option><option>En curso</option><option>En espera</option>'); }
  function openEntry(kind, item=null){ editing=item?{kind,id:item.id}:null; $('#dialogType').textContent=item?'EDITAR REGISTRO':'NUEVO REGISTRO'; $('#dialogTitle').textContent=item?'Editar '+({client:'cliente',opportunity:'oportunidad',task:'tarea'}[kind]):'Nuevo '+({client:'cliente',opportunity:'oportunidad',task:'tarea'}[kind]); els.fields.innerHTML=formFields(kind,item||{}); els.form.dataset.kind=kind; if(item) Object.entries(item).forEach(([k,v])=>{const e=els.form.elements[k];if(e)e.value=v??''}); els.entry.showModal(); els.form.querySelector('input')?.focus(); }
  function details(kind,id){ const group=kind==='client'?'clients':kind==='opportunity'?'opportunities':'tasks',item=data[group].find(x=>x.id===id); if(!item)return; editing={kind,id}; const names={name:'Nombre',title:'Tarea',company:'Empresa',service:'Servicio',contact:'Contacto',email:'Correo',phone:'Teléfono',status:'Estado',nextAction:'Próxima acción',notes:'Notas',client:'Cliente / empresa',value:'Valor estimado',stage:'Etapa',owner:'Responsable',due:'Fecha límite',priority:'Prioridad'};
    const fields=(source,omit=['id','completed'])=>`<div class="detail-list">${Object.entries(source).filter(([k])=>!omit.includes(k)).map(([k,v])=>`<div class="detail-item ${k==='notes'||k==='nextAction'?'full':''}"><span>${names[k]||k}</span><b>${k==='value'?money(v):esc(v||'—')}</b></div>`).join('')}</div>`;
    if(kind!=='client'){ $('#detailBody').innerHTML=`<div class="dialog-head"><div><p class="eyebrow">${kind==='opportunity'?'OPORTUNIDAD':'TAREA'}</p><h2 id="detailTitle">${esc(item.name||item.title)}</h2></div><button class="close-button" id="detailClose" aria-label="Cerrar">Cerrar</button></div>${fields(item)}`; $('#detailClose').onclick=()=>els.detail.close(); els.detail.showModal(); return; }
    const clientKeys=[item.name,item.company].map(v=>(v||'').trim().toLowerCase()).filter(Boolean), belongs=x=>clientKeys.includes((x.client||'').trim().toLowerCase()); const relatedOps=data.opportunities.filter(belongs), relatedTasks=data.tasks.filter(belongs);
    const general=fields(item), service=`<div class="detail-list"><div class="detail-item full"><span>Servicio</span><b>${esc(item.service||'No se ha registrado un servicio para este cliente.')}</b></div></div>`, activity=(relatedOps.length||relatedTasks.length)?`<div class="activity-list">${relatedOps.map(o=>`<div class="activity-row"><b>${esc(o.name)}</b><small>Oportunidad, ${esc(o.stage||'Sin etapa')}</small></div>`).join('')}${relatedTasks.map(t=>`<div class="activity-row"><b>${esc(t.title)}</b><small>Tarea, ${t.completed?'Completada':'Activa'}${t.due?', '+esc(t.due):''}</small></div>`).join('')}</div>`:'<div class="activity-list"><p class="stage-empty">No hay oportunidades ni tareas vinculadas a este cliente.</p></div>';
    $('#detailBody').innerHTML=`<div class="detail-hero"><p class="eyebrow">CLIENTE</p><h2 id="detailTitle">${esc(item.name)}</h2><p>${esc(item.company||'Sin empresa')}</p>${label(item.status||'Sin estado')}</div><div class="detail-tabs" role="tablist" aria-label="Información del cliente"><button class="detail-tab active" role="tab" aria-selected="true" data-tab="general">General</button><button class="detail-tab" role="tab" aria-selected="false" data-tab="services">Servicios</button><button class="detail-tab" role="tab" aria-selected="false" data-tab="activity">Actividad</button></div><div id="clientTabContent">${general}</div>`;
    $('#clientTabContent').dataset.general=general; $('#clientTabContent').dataset.services=service; $('#clientTabContent').dataset.activity=activity; els.detail.showModal();
  }
  function toast(msg){ clearTimeout(toastTimer);els.toast.textContent=msg;els.toast.classList.add('show');toastTimer=setTimeout(()=>els.toast.classList.remove('show'),2300); }
  document.addEventListener('click', e=>{ const add=e.target.closest('[data-add]');if(add)openEntry(add.dataset.add);const nav=e.target.closest('[data-view]');if(nav){view=nav.dataset.view;render();closeMenu()}const det=e.target.closest('[data-detail]');if(det)details(det.dataset.detail,det.dataset.id);const fil=e.target.closest('[data-filter]');if(fil){taskFilter=fil.dataset.filter;tasks()}if(e.target.id==='exportData'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='aida-os-respaldo.json';a.click();URL.revokeObjectURL(a.href)}if(e.target.id==='importData')$('#importInput').click();if(e.target.id==='clearData'&&confirm('¿Borrar todo el espacio local? Esta acción no se puede deshacer.')){data=structuredClone(defaults);save();render();toast('Espacio de trabajo borrado.')} });
  els.form.addEventListener('submit',e=>{e.preventDefault();const kind=els.form.dataset.kind, values=Object.fromEntries(new FormData(els.form));const group=kind==='client'?'clients':kind==='opportunity'?'opportunities':'tasks';const saveButton=$('#saveButton');els.form.setAttribute('aria-busy','true');saveButton.textContent='Guardando…';saveButton.disabled=true;if(editing){const i=data[group].findIndex(x=>x.id===editing.id);data[group][i]={...data[group][i],...values};toast('Cambios guardados.')}else{data[group].unshift({...values,id:id(),...(kind==='task'?{completed:false}:{})});toast('Registro guardado.')}save();els.form.removeAttribute('aria-busy');saveButton.textContent='Guardar';saveButton.disabled=false;els.entry.close();render();});
  document.addEventListener('change',e=>{if(e.target.classList.contains('task-check')){const t=data.tasks.find(x=>x.id===e.target.dataset.id);t.completed=e.target.checked;save();tasks();toast(t.completed?'Tarea completada.':'Tarea reabierta.')} });
  $('#detailCloseBottom').onclick=()=>els.detail.close();$('#detailEdit').onclick=()=>{els.detail.close();const g=editing.kind==='client'?'clients':editing.kind==='opportunity'?'opportunities':'tasks';openEntry(editing.kind,data[g].find(x=>x.id===editing.id));};$('#detailDelete').onclick=()=>{if(!editing)return;const g=editing.kind==='client'?'clients':editing.kind==='opportunity'?'opportunities':'tasks';if(confirm('¿Eliminar este registro? Esta acción no se puede deshacer.')){data[g]=data[g].filter(x=>x.id!==editing.id);save();els.detail.close();render();toast('Registro eliminado.')}};
  document.addEventListener('click',e=>{const tab=e.target.closest('.detail-tab');if(!tab)return;const content=$('#clientTabContent');if(!content)return;document.querySelectorAll('.detail-tab').forEach(x=>{const selected=x===tab;x.classList.toggle('active',selected);x.setAttribute('aria-selected',selected)});content.innerHTML=content.dataset[tab.dataset.tab];});
  $('#newButton').onclick=$('#mobileNew').onclick=()=>els.command.showModal();$('#commandClose').onclick=()=>els.command.close();document.querySelectorAll('.command-list button').forEach(b=>b.onclick=()=>{els.command.close();openEntry(b.dataset.kind)});
  $('#importInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!d||!['clients','opportunities','tasks'].every(k=>Array.isArray(d[k])))throw Error();if(confirm('¿Reemplazar los datos actuales con este respaldo?')){data=d;save();render();toast('Respaldo importado.')}}catch{alert('El archivo no tiene el formato de respaldo de AIDA OS.')}};r.readAsText(f);e.target.value='';});
  $('#searchInput').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();if(!q){render();return}const found=[...data.clients.map(x=>({...x,_:'client',title:x.name})),...data.opportunities.map(x=>({...x,_:'opportunity',title:x.name})),...data.tasks.map(x=>({...x,_:'task',title:x.title}))].filter(x=>Object.values(x).some(v=>String(v).toLowerCase().includes(q)));els.title.textContent='Búsqueda';els.content.innerHTML=`<div class="module"><div class="module-head"><div><h2>${found.length} resultado${found.length===1?'':'s'}</h2><p>Coincidencias para “${esc(e.target.value)}”.</p></div></div>${found.length?`<section class="records">${found.map(x=>`<button class="record" data-detail="${x._}" data-id="${x.id}"><div><b>${esc(x.title)}</b><small>${x._==='client'?'Cliente':x._==='opportunity'?'Oportunidad':'Tarea'}</small></div><div class="hide-mobile">${esc(x.client||x.company||x.service||'')}</div><div></div><div>${label(x.status||x.stage||x.priority||'')}</div></button>`).join('')}</section>`:'<section class="empty"><h3>No encontramos registros</h3><p>Prueba otro término o crea un registro nuevo.</p></section>'}</div>`;});
  function closeMenu(){$('#sidebar').classList.remove('open');$('#backdrop').classList.remove('active');$('#menuButton').setAttribute('aria-expanded','false')}$('#menuButton').onclick=()=>{const open=$('#sidebar').classList.toggle('open');$('#backdrop').classList.toggle('active',open);$('#menuButton').setAttribute('aria-expanded',open)};$('#backdrop').onclick=closeMenu;
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();return}if(e.key.toLowerCase()==='n'&&!e.metaKey&&!e.ctrlKey&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();els.command.showModal()}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchInput').focus()}});
  today();render();
})();
