// Integraciones disponibles: textos y campos de cada formulario de conexión.
type Field = { name: string; label: string; type?: string; placeholder?: string; hint?: string }
export type IntegrationDef = { key: 'claude' | 'openai' | 'gemini' | 'whatsapp' | 'email' | 'n8n'; name: string; icon: string; color: [string, string]; what: string; fields: Field[]; help: { label: string; url: string } }

export const INTEGRATION_DEFS: IntegrationDef[] = [
  { key: 'claude', name: 'Claude (Anthropic)', icon: 'C', color: ['#3a2a1e', '#e8a27a'], what: 'Redacta mensajes para clientes y resume la ficha de cada cliente.', fields: [{ name: 'apiKey', label: 'API key', type: 'password', placeholder: 'sk-ant-…' }], help: { label: 'Crear llave en console.anthropic.com', url: 'https://console.anthropic.com/settings/keys' } },
  { key: 'openai', name: 'OpenAI (ChatGPT)', icon: 'O', color: ['#12302a', '#5fddb0'], what: 'Alternativa a Claude para redactar y resumir.', fields: [{ name: 'apiKey', label: 'API key', type: 'password', placeholder: 'sk-…' }], help: { label: 'Crear llave en platform.openai.com', url: 'https://platform.openai.com/api-keys' } },
  { key: 'gemini', name: 'Gemini (Google)', icon: 'G', color: ['#163d7c', '#8fb8ff'], what: 'Alternativa a Claude para redactar y resumir.', fields: [{ name: 'apiKey', label: 'API key', type: 'password', placeholder: 'AIza…' }], help: { label: 'Crear llave en Google AI Studio', url: 'https://aistudio.google.com/apikey' } },
  { key: 'whatsapp', name: 'WhatsApp Business (API de Meta)', icon: 'W', color: ['#123e35', '#66e0ba'], what: 'Envía mensajes de WhatsApp desde la ficha del cliente, sin salir del CRM.', fields: [{ name: 'phoneNumberId', label: 'ID del número de teléfono', placeholder: '1234567890' }, { name: 'token', label: 'Token de acceso', type: 'password', placeholder: 'EAAG…', hint: 'Usa un token permanente de un usuario del sistema.' }], help: { label: 'Configurar en developers.facebook.com', url: 'https://developers.facebook.com/docs/whatsapp/cloud-api/get-started' } },
  { key: 'email', name: 'Correo (Resend)', icon: '@', color: ['#382d61', '#bda4ff'], what: 'Envía correos a clientes desde el CRM y los avisos automáticos al equipo.', fields: [{ name: 'apiKey', label: 'API key de Resend', type: 'password', placeholder: 're_…' }, { name: 'from', label: 'Remitente', placeholder: 'AIDA <hola@tudominio.com>', hint: 'El dominio debe estar verificado en Resend.' }], help: { label: 'Crear llave en resend.com', url: 'https://resend.com/api-keys' } },
  { key: 'n8n', name: 'n8n (webhooks)', icon: 'n8', color: ['#5b1f24', '#ff9b9b'], what: 'Recibe en n8n cada evento del CRM para armar tus flujos: lead nuevo, cliente ganado, pago, tarea completada…', fields: [{ name: 'url', label: 'URL del webhook (producción)', placeholder: 'https://tu-n8n.com/webhook/…', hint: 'En n8n, agrega un nodo Webhook (POST), actívalo y pega aquí su URL de producción.' }], help: { label: 'Cómo crear un webhook en n8n', url: 'https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.webhook/' } },
]

