import { ActionSubmitButton } from '@/components/ui/action-submit-button'
import { ActionFeedbackForm } from '@/components/ui/action-feedback-form'
import { completeTask, saveTask } from '@/app/actions/sales'
import { EmptyState } from '@/components/sales/empty-state'
import { selectedRecord } from '@/features/dashboard/domain/search-routes'
import { getOrganizationContext } from '@/lib/supabase/context'

export default async function TasksPage({ searchParams }: { searchParams: Promise<{ task?: string }> }) {
  const { task: requestedTask } = await searchParams
  const { supabase, organizationId } = await getOrganizationContext()
  const { data } = await supabase.from('tasks').select('id,title,priority,status,due_at').eq('organization_id', organizationId!).order('due_at')
  const allTasks = (data ?? []) as Array<{ id: string; title: string; priority: string; status: string; due_at: string | null }>
  const { records: tasks, found } = selectedRecord(allTasks, requestedTask)
  return <div className="product-grid min-h-[calc(100dvh-72px)] p-5 md:p-8"><p className="mono text-xs uppercase tracking-[.16em] text-brand-primary">Trabajo / Tareas</p><h1 className="mt-2 text-3xl font-bold tracking-[-.06em]">Tareas</h1>{requestedTask && !found && <p role="alert" className="mt-4 text-sm text-brand-muted">La tarea solicitada no existe o no está disponible para tu organización.</p>}<div className="mt-7 grid gap-6 lg:grid-cols-[360px_1fr]"><ActionFeedbackForm action={saveTask} successMessage="Tarea creada correctamente" className="border border-brand-border bg-brand-surface-elevated p-5"><h2 className="font-semibold">Nueva tarea</h2><input required name="title" placeholder="Qué hay que hacer" className="mt-4 w-full border border-brand-border bg-brand-bg p-2.5"/><textarea name="description" placeholder="Contexto" className="mt-3 w-full border border-brand-border bg-brand-bg p-2.5"/><div className="mt-3 grid grid-cols-2 gap-3"><select name="priority" className="border border-brand-border bg-brand-bg p-2.5"><option value="medium">Media</option><option value="high">Alta</option><option value="low">Baja</option></select><input name="dueAt" type="date" className="border border-brand-border bg-brand-bg p-2.5"/></div><ActionSubmitButton className="mt-4 w-full bg-brand-text p-2.5 text-sm font-medium text-brand-bg">Crear tarea</ActionSubmitButton></ActionFeedbackForm>{tasks.length === 0 ? <EmptyState title={requestedTask ? 'No se encontró esa tarea.' : 'No hay tareas pendientes.'}/> : <ul className="divide-y divide-brand-border border border-brand-border bg-brand-surface-elevated">{tasks.map((task) => <li id={`task-${task.id}`} key={task.id} className="flex items-start justify-between gap-4 p-4"><div><p className={task.status === 'completed' ? 'text-brand-muted line-through' : 'font-medium'}>{task.title}</p><p className="mt-1 text-sm text-brand-muted">{task.priority} {task.due_at && `· ${new Date(task.due_at).toLocaleDateString('es-EC')}`}</p></div><ActionFeedbackForm action={completeTask} successMessage="Tarea actualizada correctamente"><input type="hidden" name="id" value={task.id}/><input type="hidden" name="completed" value={task.status === 'completed' ? 'false' : 'true'}/><ActionSubmitButton className="text-sm">{task.status === 'completed' ? 'Reabrir' : 'Completar'}</ActionSubmitButton></ActionFeedbackForm></li>)}</ul>}</div></div>
}
