-- AutomAI CRM OS — Operations intelligence (strictly additive; no DROP/DELETE/TRUNCATE).
do $$ begin create type public.automation_status as enum ('disabled','active','error'); exception when duplicate_object then null; end $$;
do $$ begin create type public.webhook_event_status as enum ('received','processing','delivered','failed','dead_letter'); exception when duplicate_object then null; end $$;
do $$ begin create type public.hermes_intent_status as enum ('pending_confirmation','confirmed','cancelled','executed'); exception when duplicate_object then null; end $$;

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, recipient_id uuid not null references auth.users(id) on delete cascade,
  group_key text, title text not null check (char_length(trim(title)) between 1 and 180), body text, kind text not null default 'system', entity_type text, entity_id uuid, read_at timestamptz, created_at timestamptz not null default now(), created_by uuid references auth.users(id) on delete set null
);
create table if not exists public.automations (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, name text not null check (char_length(trim(name)) between 2 and 120), event_type text not null check (event_type in ('deal.won','invoice.paid','task.completed','project.completed')), webhook_url text not null check (webhook_url ~ '^https://'), status public.automation_status not null default 'disabled', last_delivered_at timestamptz, last_error text, last_error_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id) on delete set null
);
create table if not exists public.webhook_events (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, automation_id uuid references public.automations(id) on delete set null, idempotency_key text not null check (char_length(trim(idempotency_key)) between 8 and 255), event_type text not null, payload jsonb not null default '{}'::jsonb, status public.webhook_event_status not null default 'received', attempt_count integer not null default 0 check (attempt_count >= 0), next_retry_at timestamptz, response_status integer, response_body text, error_message text, delivered_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (organization_id, idempotency_key)
);
create table if not exists public.files (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, storage_bucket text not null check (storage_bucket ~ '^[a-z0-9][a-z0-9_-]{1,62}$'), storage_path text not null check (storage_path !~ '(^/|\\.\\.)'), file_name text not null check (char_length(trim(file_name)) between 1 and 255), mime_type text, byte_size bigint check (byte_size >= 0), entity_type text, entity_id uuid, created_at timestamptz not null default now(), created_by uuid references auth.users(id) on delete set null, unique (organization_id, storage_bucket, storage_path)
);
create table if not exists public.tags (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, name text not null check (char_length(trim(name)) between 1 and 60), color text not null default '#6F6B64' check (color ~ '^#[0-9A-Fa-f]{6}$'), created_at timestamptz not null default now(), created_by uuid references auth.users(id) on delete set null, unique (organization_id, name));
create table if not exists public.entity_tags (organization_id uuid not null references public.organizations(id) on delete cascade, tag_id uuid not null references public.tags(id) on delete cascade, entity_type text not null check (entity_type in ('company','contact','deal','project','invoice')), entity_id uuid not null, created_at timestamptz not null default now(), created_by uuid references auth.users(id) on delete set null, primary key (tag_id, entity_type, entity_id));
create table if not exists public.monthly_goal_history (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, month date not null check (date_trunc('month', month)::date = month), monthly_revenue_goal numeric(12,2) not null check (monthly_revenue_goal >= 0), mrr_goal numeric(12,2) not null check (mrr_goal >= 0), created_at timestamptz not null default now(), created_by uuid references auth.users(id) on delete set null, unique (organization_id, month));
create table if not exists public.hermes_mutation_intents (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, tool_name text not null check (tool_name in ('create_task','log_activity','update_deal')), payload jsonb not null default '{}'::jsonb, confirmation_status public.hermes_intent_status not null default 'pending_confirmation', requested_by uuid not null references auth.users(id) on delete cascade, confirmed_at timestamptz, created_at timestamptz not null default now());

create index if not exists notifications_recipient_unread_idx on public.notifications (organization_id, recipient_id, read_at, created_at desc); create index if not exists automations_org_event_idx on public.automations (organization_id, event_type, status); create index if not exists webhook_events_retry_idx on public.webhook_events (organization_id, status, next_retry_at); create index if not exists files_entity_idx on public.files (organization_id, entity_type, entity_id); create index if not exists entity_tags_entity_idx on public.entity_tags (organization_id, entity_type, entity_id);
create trigger automations_updated_at before update on public.automations for each row execute procedure public.set_updated_at(); create trigger webhook_events_updated_at before update on public.webhook_events for each row execute procedure public.set_updated_at();
create trigger audit_automations after insert or update or delete on public.automations for each row execute procedure public.audit_sensitive_change(); create trigger audit_webhook_events after insert or update or delete on public.webhook_events for each row execute procedure public.audit_sensitive_change(); create trigger audit_files after insert or update or delete on public.files for each row execute procedure public.audit_sensitive_change(); create trigger audit_tags after insert or update or delete on public.tags for each row execute procedure public.audit_sensitive_change(); create trigger audit_goal_history after insert or update or delete on public.monthly_goal_history for each row execute procedure public.audit_sensitive_change(); create trigger audit_hermes_intents after insert or update or delete on public.hermes_mutation_intents for each row execute procedure public.audit_sensitive_change();

insert into public.permissions (key, description) values ('operations.read','Consultar operaciones, notificaciones y automatizaciones'),('operations.write','Gestionar automatizaciones y etiquetas'),('analytics.read','Consultar analítica de ventas e ingresos'),('settings.write','Gestionar metas e integraciones') on conflict do nothing;
insert into public.role_permissions (role_key, permission_key) values ('owner','operations.read'),('owner','operations.write'),('owner','analytics.read'),('owner','settings.write'),('admin','operations.read'),('admin','operations.write'),('admin','analytics.read'),('admin','settings.write'),('sales','operations.read'),('sales','analytics.read'),('operations','operations.read'),('operations','analytics.read'),('finance','analytics.read'),('viewer','analytics.read') on conflict do nothing;
alter table public.notifications enable row level security; alter table public.automations enable row level security; alter table public.webhook_events enable row level security; alter table public.files enable row level security; alter table public.tags enable row level security; alter table public.entity_tags enable row level security; alter table public.monthly_goal_history enable row level security; alter table public.hermes_mutation_intents enable row level security;
create policy notifications_access on public.notifications for all using (organization_id in (select organization_id from public.user_roles where user_id = auth.uid()) and recipient_id = auth.uid()) with check (organization_id in (select organization_id from public.user_roles where user_id = auth.uid()) and recipient_id = auth.uid());
create policy automations_access on public.automations for all using (public.has_permission(organization_id,'operations.read')) with check (public.has_permission(organization_id,'operations.write'));
create policy webhook_events_access on public.webhook_events for select using (public.has_permission(organization_id,'operations.read')); create policy files_access on public.files for all using (public.has_permission(organization_id,'operations.read')) with check (public.has_permission(organization_id,'operations.write')); create policy tags_access on public.tags for all using (public.has_permission(organization_id,'operations.read')) with check (public.has_permission(organization_id,'operations.write')); create policy entity_tags_access on public.entity_tags for all using (public.has_permission(organization_id,'operations.read')) with check (public.has_permission(organization_id,'operations.write')); create policy monthly_goal_history_access on public.monthly_goal_history for select using (public.has_permission(organization_id,'analytics.read')); create policy hermes_intents_access on public.hermes_mutation_intents for all using (requested_by = auth.uid() and organization_id in (select organization_id from public.user_roles where user_id = auth.uid())) with check (requested_by = auth.uid() and organization_id in (select organization_id from public.user_roles where user_id = auth.uid()));
