import { ActionSubmitButton } from '@/components/ui/action-submit-button'
import { ActionFeedbackForm } from '@/components/ui/action-feedback-form'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { recordPayment } from '@/app/actions/commercial'
import { calculateInvoiceBalance } from '@/features/finance/domain/revenue-metrics'
import { getOrganizationContext } from '@/lib/supabase/context'

const methods: Record<string, string> = { bank_transfer: 'Transferencia', cash: 'Efectivo', card: 'Tarjeta', other: 'Otro' }
export default async function InvoiceDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const { supabase, organizationId } = await getOrganizationContext()
  const { data } = await supabase.from('invoices').select('id,number,status,total,issue_date,due_date,companies(name),payments(amount,paid_at,method,reference)').eq('id', id).eq('organization_id', organizationId!).maybeSingle()
  if (!data) notFound()
  const invoice = data as unknown as { id: string; number: string; status: string; total: number; issue_date: string; due_date: string; companies: { name: string } | null; payments: Array<{ amount: number; paid_at: string; method: string; reference: string | null }> }
  const paid = invoice.payments.reduce((sum, payment) => sum + Number(payment.amount), 0)
  const remaining = calculateInvoiceBalance({ total: Number(invoice.total), payments: invoice.payments.map((payment) => Number(payment.amount)) })
  const money = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' })
  return <main className="product-grid min-h-[calc(100dvh-72px)] p-5 md:p-8"><Link href="/finance/invoices" className="text-sm text-brand-primary underline">Volver a facturas</Link><p className="mono mt-5 text-xs uppercase tracking-[.16em] text-brand-primary">Finanzas / Factura</p><h1 className="mt-2 text-3xl font-bold tracking-[-.06em]">{invoice.number}</h1><p className="mt-2 text-brand-muted">{invoice.companies?.name ?? 'Sin empresa vinculada'} · {invoice.status}</p><dl className="mt-6 grid gap-3 border border-brand-border bg-brand-surface-elevated p-4 sm:grid-cols-3"><div><dt className="text-sm text-brand-muted">Total</dt><dd>{money.format(Number(invoice.total))}</dd></div><div><dt className="text-sm text-brand-muted">Cobrado</dt><dd>{money.format(paid)}</dd></div><div><dt className="text-sm text-brand-muted">Saldo pendiente</dt><dd>{money.format(remaining)}</dd></div></dl><p className="mt-4 text-sm text-brand-muted">Emitida: {invoice.issue_date} · Vence: {invoice.due_date}</p><section className="mt-6 border border-brand-border bg-brand-surface-elevated p-4"><h2 className="font-semibold">Historial de pagos</h2>{invoice.payments.length ? <ul className="mt-3 space-y-2">{invoice.payments.map((payment, index) => <li key={`${payment.paid_at}-${index}`} className="text-sm">{payment.paid_at.slice(0, 10)} · {money.format(Number(payment.amount))} · {methods[payment.method] ?? payment.method}{payment.reference ? ` · Ref. ${payment.reference}` : ''}</li>)}</ul> : <p className="mt-3 text-sm text-brand-muted">Todavía no hay pagos registrados.</p>}</section>{['issued', 'partial', 'overdue'].includes(invoice.status) && <ActionFeedbackForm action={recordPayment} successMessage="Cobro registrado correctamente" className="mt-6 max-w-2xl border border-brand-border bg-brand-surface-elevated p-4"><h2 className="font-semibold">Registrar pago</h2><input type="hidden" name="invoiceId" value={invoice.id}/><div className="mt-3 grid gap-2 sm:grid-cols-2"><input required name="amount" min="0.01" max={remaining} step="0.01" type="number" placeholder="Cobro" className="border border-brand-border bg-brand-bg p-2"/><input required name="paidAt" aria-label="Fecha de pago" type="date" className="border border-brand-border bg-brand-bg p-2"/><select required name="method" aria-label="Método de pago" className="border border-brand-border bg-brand-bg p-2"><option value="">Método</option>{Object.entries(methods).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><input name="reference" placeholder="Referencia (opcional)" className="border border-brand-border bg-brand-bg p-2"/></div><ActionSubmitButton className="mt-3 text-sm">Registrar pago</ActionSubmitButton></ActionFeedbackForm>}</main>
}
